### ISSUE TITLE
Время последнего вызова по cron указывается без учета часового пояса.

### ISSUE THREAD

**Issue by progreccor** [Joomline/jlsitemap#10]
![2018-11-02_20-46-37 2](https://user-images.githubusercontent.com/3103677/47932187-043ecd80-dee2-11e8-8cbf-fb84b4a3b70c.png)

![2018-11-02_20-46-57 2](https://user-images.githubusercontent.com/3103677/47932105-cb065d80-dee1-11e8-836a-ec592b5a93ba.png)

**Comment by Septdir** [comment]
closed this in [368ddf5](https://github.com/Joomline/jlsitemap/commit/368ddf5cefbbd08703b4822ef5e399e37c887a32)
