### ISSUE TITLE
Сделать совместимость с плагинами XMAP

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/jlsitemap#11]
Суть в чем, мы можем сделать плагины для действительно популярных расширений, но у нас есть целый вагон расширений, которые не очень популярны, но для них сделаны плагины XMAP, и если мы вдруг сделаем совместимость, то мы резко охватим почти все расширения Joomla.

**Comment by Septdir** [comment]
То есть, сделал совместимость, а пока не торопясь пилить свои плагины?

**Comment by zikkuratvk** [comment]
Ну по идее это просто сделает огромный охват совместимости со всем и вся, что только есть.

**Comment by Septdir** [comment]
Ну я попытался когда за отдельный класс за 1к строк перевалил бросил, там вообще нет return как такового И без либы к примеру osmap'овской не получиться.

**Comment by zikkuratvk** [comment]
ок давай тогда закрываем это обсуждение :-) пускай делают совместимость с нами.
Если ты не заметил OSmap сам по себе адовую нагрузку дает.
