### ISSUE TITLE
Ссылка на адрес для вызова cron

### ISSUE THREAD

**Issue by progreccor** [Joomline/jlsitemap#2]
В компоненте нужно предусмотреть где-то вывод адреса для вызова задачи cron для генерации карты сайта. Чтобы человек мог просто скопировать адрес и вставить его в cron.

**Comment by Septdir** [comment]
Ссылку то не проблема сделать. Добавим фронтальный контролер и все.

Но я вот думаю как бы сделать так чтобы можно было и без крона раз в n времени генерировать.

Понятно что через системный плагин. Но вот как сделать чтобы посетитель этого не заметил.

**Comment by progreccor** [comment]
такое делать не очень хорошо. Человек, который натолкнется на генерацию карты сайта будет долго ждать. еще хуже если это окажется паук, который может оборвать соединение.

Лучше всего просто не разрешать такое.
но хозяин - барин.
полагаемся на пауков и юзеров

**Comment by Septdir** [comment]
@progreccor Вот я и думаю как сделать чтобы человек не ждал. 

А ссылку на com_ajax можно будет и в cron засунуть. В общем надо подумать как сделать.

**Comment by progreccor** [comment]
средствами нормального php, который доступен в хостингах - никак.
php - однопоточный язык и ничего не поделать.

Единственный корректный вариант - вызывать крон. 

Еще один нехороший вариант - внедрить javascript который независимо от основной страницы вызовет аякс, который уже сможет вызвать генерацию карты.

Но это все из разряда не сильно хороших идей. Завязывать такие важные вещи на посетителей - не сильно хорошая идея. 

Правда других нет - только cron.

Зато можно предложить свой cron сервис за деньги ;-)

**Comment by Septdir** [comment]
@progreccor Вот я и думаю надо вторым вариантом.

Ну точнее над обоими.
Нормальным людям просто выводить ссылку для крона.
А остальным, дать опцию `повесить на посетителей`

**Comment by progreccor** [comment]
если вешать на посетителей то только один вариант - ява скрипт

**Comment by Septdir** [comment]
@progreccor Кто бы его дал, а то  только на Jquery умею.

**Comment by progreccor** [comment]
так там просто задание повесить
есть готовые уже

**Comment by Septdir** [comment]
@progreccor Можешь скинуть? Чтобы мне не гуглить. толкьо JS остальное я сам сделаю.

**Comment by Septdir** [comment]
@progreccor По идеи так?

```
try {
    document.addEventListener('DOMContentLoaded', function () {
        var xmlhttp = new XMLHttpRequest();
        xhttp.open("GET", "ajaxurl", true);
        xhttp.send();
    });
} catch (e) {
    console.error('Custom Theme JS Code: ', e);
}
```

**Comment by progreccor** [comment]
да, вроде должно работать. учти что код надо выводить только тому юзеру, который попадает под временной интервал. остальным лишний код ни к чему.

**Comment by Septdir** [comment]
@progreccor Сделаю 2 временных проверки. Одна будет на вывод кода. Другая будет уже в самом обработчике. С за пуском от посетителей разобрались, в теории.

Теперь с классическим кроном. Делать какие нибудь проверки?

**Comment by dmitrystas** [comment]
Генерацию можно вызывать не на фронте, а только в админке

**Comment by zikkuratvk** [comment]
Предлагаю по крону сделать так... сделать запуск просто по ссылке с уникальным ключом, а остальное оставить для дальнейшего развития.

**Comment by progreccor** [comment]
> 
> 
> @progreccor Сделаю 2 временных проверки. Одна будет на вывод кода. Другая будет уже в самом обработчике. С за пуском от посетителей разобрались, в теории.
> 
> Теперь с классическим кроном. Делать какие нибудь проверки?

учти один тонкий момент - если будешь проверять время в клиенте - у него может быть свой часовой пояс...

**Comment by Septdir** [comment]
@progreccor Насколько я помню JDate это умеет учитывать.

**Comment by zikkuratvk** [comment]
Для карты сайта не критично когда она будет генерироваться... В 12 или в 13
