### ISSUE TITLE
[plg_system_jlsitemap_cron] Более подробная документация под ссылкой

### ISSUE THREAD

**Issue by Septdir** [Joomline/jlsitemap#20]
Сейчас по ссылкой короткая строка с очевидным текстом "Ссылка для планировщика".

Возможно стоит добавить туда более подробную инструкцию?

К примеру. Я могу дергать файл и вставлять код с него туда. или iframe можно.

**Comment by progreccor** [comment]
есть парочка хороших ссылок, которые были бы там уместны.
https://crontab-generator.org/
https://crontab.guru/#00_21_*_*_*

помогают создавать cron задания.

**Comment by zikkuratvk** [comment]
f4a19e75867107cf8dda29c536d312358cff8f8e
