### ISSUE TITLE
Добавить фильтрацию по ссылке 

### ISSUE THREAD

**Issue by Septdir** [Joomline/jlsitemap#25]
Добавить настройки компонента textarea, которая будет позволять фильтровать карту сайта по содержанию в ссылке значение фильтра.

**Comment by effrit** [comment]
textarea удобнее для ввода, и нагляднее, чем для 10 слов 10 полей генерировать

**Comment by Septdir** [comment]
@effrit почему же 10. Обычный miltiple text field с двумя кнопочками рядом. + и -

У меня есть такие поля готовые, чуть подправить и готово.

Можно конечно texarea но том по новой строке explode делать, не особо люблю.

К тому писать эту фразу типа. Каждое значение в новой строке.

**Comment by Septdir** [comment]
@effrit то что на картинке 1/4 экрана? по ширине будет такая же как и textarea ну ладно на 40px больше.

**Comment by effrit** [comment]
это не удобно, когда надо просто список скопировать, например.
explode по \n+ trim, если не хочешь регулярку использовать. и не надо его любить, он не для этого )

**Comment by Septdir** [comment]
@effrit \n лучше не делать, лучше по PHP_EOL а самый надежный вариант регуляркой, он меня ни разу не подводил.

**Comment by effrit** [comment]
я читал недавно про это.
_EOL от системы зависит, так что не надежно, \n сработает, а trim убирает \r, если было. 
ну или регулярка

**Comment by Septdir** [comment]
Регулярка и trim чтобы наверника.
Так и запишем.
textarea
