### ISSUE TITLE
[plg_system_jlsitemap_cron] Опечатки

### ISSUE THREAD

**Issue by exstreme** [Joomline/jlsitemap#27]
ru-RU.plg_system_jlsitemap_cron.ini

PLG_SYSTEM_JLSITEMAP_CRON_PARAMS_CLIENT_MODE = "Заускать"
PLG_SYSTEM_JLSITEMAP_CRON_PARAMS_CLIENT_MODE_ADMIN = "Адинка"

**Comment by zikkuratvk** [comment]
f0dd0ae84938422643aecbad596d41f27250a007
