### ISSUE TITLE
Более понятные сообщения о завершении

### ISSUE THREAD

**Issue by Septdir** [Joomline/jlsitemap#33]
Ориентировочный вариант от @progreccor 

> Генерация карты сайта завершена. Всего было 10 ссылок
> Исключено: 4 ( в соответствии с правилами фильтрации (ссылка))
> В итоге карта сайта состоит из 6 адресов

**Comment by progreccor** [comment]
Уточненный вариант:

- Генерация карты сайта завершена. Всего обработано 10 ссылок
- Исключено: 4 ( в соответствии с правилами фильтрации (ссылка))
- Итого осталось в карте сайта: 6 ссылок.
