### ISSUE TITLE
При отключения префикса у основного языка не правильная генерация url

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/jlsitemap#35]
Английский версия сайта правильная ссылка будет: https://joomline.net/forum.html 
Карта сайта генерирует вот такую ссылку: https://joomline.net/en/forum.html

**Comment by Septdir** [comment]
@zikkuratvk Не могу воспроизвести. Ты уверен что у тебя включено удаления префикса из url?

**Comment by Septdir** [comment]
А все поймал.
Дело в том по какому урл генерироваться карту.
