### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by Septdir** [Joomline/jlsitemap#36]
Нужен ли CLI для JL Sitemap.

Если наберется достаточно людей которым это нужно, можно будет попробовать сделать что-то.

**Comment by kernusr** [comment]
Мне нада!

**Comment by Septdir** [comment]
После 2-х часов ковыряния я выяснил 
1. На мультязычном сайте не работает мультязычность, ибо cli не web
2. Иногда ссылки не коректно строятся, даже если это одноязычный сайт и хост прописан.

Итого не выйдет сделать на массу.

**Comment by kernusr** [comment]
А где конкретно баг с ссылками?
Можешь подробнее рассказать?

**Comment by Septdir** [comment]
Router по просту не видет мультиязычность. И думаю поддеокторию тоже.
Так что Web  application заставить его нормально работать не реально.
Для одно язычного конкретного сайта можно сделать cli на массу не реально.
