### ISSUE TITLE
 Добавить плагин для ZOO

### ISSUE THREAD

**Issue by Sulpher** [Joomline/jlsitemap#37]
Предлагаю добавить плагин поддержки ZOO CCK. 
Помогу с тестированием.

**Comment by SamusUA** [comment]
> Предлагаю добавить плагин поддержки ZOO CCK.
+1

**Comment by fiction13** [comment]
> Предлагаю добавить плагин поддержки ZOO CCK.
> Помогу с тестированием.

Вот держите ;-) [https://fictionlabs.ru/razrabotka/jlsitemap-zoo-plagin-karty-sajta-dlya-zoo-joomla](https://fictionlabs.ru/razrabotka/jlsitemap-zoo-plagin-karty-sajta-dlya-zoo-joomla)

**Comment by zikkuratvk** [comment]
Добавил ссылку на страницу расширения.
