### ISSUE TITLE
Карта генерируется с тотальным удалением форматирования

### ISSUE THREAD

**Issue by bsakhanov** [Joomline/jlsitemap#49]
Последние версии карты 1.5.x просто все пробелы и теги удаляют без разбору:
![2019-03-13_023113](https://user-images.githubusercontent.com/45456925/54233895-1b4c9680-4538-11e9-94ce-09aeb0130936.jpg)

Приходится пользоваться версией 1.4.0 -- в ней все нормально генерируется:
![2019-03-13_023233](https://user-images.githubusercontent.com/45456925/54233984-4d5df880-4538-11e9-8214-a99946766fd9.jpg)
просьба исправить баг!

**Comment by Septdir** [comment]
Карта генерируется одинаково.  Вы можете убедиться в этом открыв исходный код. 
На втором скриншоте просто красивое отображение браузером.

В версиях 1.5.x была добавлена поддержка мультязычных карт сайта и исправлена валидность этих карт для поисковиков.

Однако, браузеры не могут нормально отображать такую карту.
То есть с картой сайта все в порядке. Просто ваш браузер не может ее корректно отобразить. 

Если вы хотите удобно посмотреть какие ссылки попадают в карту, а какие нет рекомендую нажать на "Отладка" в панели управления.

Красивый стиль xml карты сайта есть планах #48 и будет добавлен позже.

**Comment by bsakhanov** [comment]
Что-то не догадался даже на исходный код посмотреть.... Спасибо, Игорь! Вопрос снят!!! Компонент просто великолепный!
