### ISSUE TITLE
Ошибка генерации карты

### ISSUE THREAD

**Issue by Yuribtr** [Joomline/jlsitemap#53]
После установки, нажимаю кнопку Generation, и вываливается ошибка 500. При запуске генерации по ссылке из раздела "Cron" выдается сообщение:
"Exception: Не удалось сгенерировать карту сайта: Error decoding JSON data: Syntax error"

Версия Joomla 3.9.12, PHP 7.3.8, JL Sitemap 1.7.0
PHP max_execution_time = 60,  memory_limit = 128 Мб
количество материалов на сайте ~300 шт
сервер VPS (не shared)

**Comment by Septdir** [comment]
Проверьте вот этот коммент https://github.com/Joomline/jlsitemap/commit/27ab9bbec60c6e4d1698814f9870852559e8879b
А так же пришлике лог или трассировку ошибки.
Трасировку можно посмореть включив отладку в общих настройках, ну логи лежать на сервер. 
В общем нужно что-то где будет написанно на кокой именно строке ошибка

**Comment by Yuribtr** [comment]
В плагине присутствует исправленная строка из вашего коммита:
`$files = Folder::files(JPATH_ROOT, 'sitemap_[0-9]*\.xml', false, true);`

Похоже что это ошибка доступа к файлу, так как нечто [похожее уже обсуждали на вашем форуме](https://joomline.net/ru/forum/jlsitemap/6349.html). Но не было понятно какой именно файл имелся ввиду. 

Попробую вариант с трассировкой.

**Comment by Yuribtr** [comment]
С трассировкой ничего не получается. Включаю дебаг и на масимум уровень вывода ошибок в конфигурации Джумлы. Делаю попытки генерации карты через кнопку и по ссылке. 
В папке logs Джумлы лежит error.php в котором есть ошибки авторизации, но больше ничего нет. Также в этой папке обнаруживается jcontroller.log.php, в котором тоже ничего существенного нет.
Включаю журнал PHP ошибок через htaccess:
```
php_value log_errors "On"
php_value error_reporting 8191
php_value error_log /home/mysite/logs/php_errors.log
```
предварительно создаю php_errors.log, и назначаю ему права 777, однако он остается пустым, после попыток генерации sitemap.

**Comment by Septdir** [comment]
При 500 ошибке должны весьтись логи непростредвенно сервера.
Спросите у вашего хостера и он подскажет где вам их искать

**Comment by Septdir** [comment]
Не корректно настроен сайт/сервер.
