### ISSUE TITLE
Изменение названия sitemap.xml

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/jlsitemap#54]
Просят изменять название карты сайта для защиты от ботов, хотя я лично не вижу в этом практического смысла, но мало ли.

https://joomline.net/ru/forum/jlsitemap/6406.html

**Comment by Septdir** [comment]
Ну можно сделать, в настройках, но я вообще не вижу проблемы.
ибо в robots то она прописана и любой бот увидит.

**Comment by zikkuratvk** [comment]
я тоже не вижу :-)

**Comment by viocassel** [comment]
Смысла в этом чуть меньше чем никакого. Любой бот увидит карту сайта если она есть, под любым названием.
