### ISSUE TITLE
Ошибка в приоритете частоты изменений

### ISSUE THREAD

**Issue by atramentus** [Joomline/jlsitemap#55]
Столкнулся с проблемой. В общих настройках компонента выставлен 1 приоритет, в плагине другой.
**Настройки компонента**
![image](https://user-images.githubusercontent.com/20991676/73555643-aedfcc00-4456-11ea-98dd-47e26a632196.png)

**Настройки плагина**
![image](https://user-images.githubusercontent.com/20991676/73555845-f9f9df00-4456-11ea-8318-75f6a1e23a4d.png)
![image](https://user-images.githubusercontent.com/20991676/73555871-02eab080-4457-11ea-842c-cf4dd35da687.png)

На скриншоте видно что частота изменений берется с компонента, а приоритет с плагина
![image](https://user-images.githubusercontent.com/20991676/73555969-33cae580-4457-11ea-8b13-60afc88d94c7.png)

**Comment by zikkuratvk** [comment]
Если мы говорим про эти пункты?

![image](https://user-images.githubusercontent.com/2261206/73556261-bfdd0d00-4457-11ea-8c71-dddda7b30876.png)
То это не материалы, по этому приоритет отдается настройкам из компонента.

**Comment by atramentus** [comment]
по идее везде, где приоритет изменился на 0,3 (это настройка пришла из плагина), также должна была измениться и частота изменений (тоже из плагина "monthly").

**Comment by zikkuratvk** [comment]
Вот теперь яснее стало :-)
Это действительно баг.

**Comment by Septdir** [comment]
Ну вот приотиет надо будет проверить ибо 1приорететнее 0.3 в остальном верно.
delaly паритетнее  mounthsly, а т.к это пункт меню то и соответственно берутся настройки компонента.

**Comment by Septdir** [comment]
Строка для проверки, чтобы не потерять
https://github.com/Joomline/jlsitemap/blob/master/com_jlsitemap/site/models/sitemap.php#L580

**Comment by atramentus** [comment]
Мне кажется логичнее было бы если бы настройки брались из плагина даже для пунктов меню.

**Прикладная задача расставить частоту и приоритеты страницам.**
Главная -- daily 1,0
Товары (не являются пунктами меню) -- weekly 0,7
Категории товаров (являются пунктами меню) -- weekly 0,8
Материалы/категории сайта (не важно являются они пунктами меню или нет) -- monthly 0,4

Если приоритет во всем отдается компоненту, то такую задачу решить невозможно т.к. настройки у категорий и у некоторых материалов/категорий перепишутся настройками компонента.

Возможно я не прав и не до конца разобрался с настройками.

**Comment by Septdir** [comment]
В целом вы правы, гибкости не хватет, однако, пункт меню приоритенее.
В будущем ест ьв панал чтобы итемам можно было ставить свои настройки.

**Comment by atramentus** [comment]
Было бы великолепно. В любом случае спасибо за компонент

**Comment by Septdir** [comment]
Для каждого отдельного итема сделал отдельный issue 
#56
