### ISSUE TITLE
Дублирование ссылки в карте сайта при разбиении на несколько

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/jlsitemap#58]
Тестирование новой версии:

https://www.38i.ru/sitemap_1.xml
https://www.38i.ru/sitemap_2.xml

Ищу ссылку 
https://www.38i.ru/auto/1263-1263

Она присутствует во всех файлах.

**Comment by Septdir** [comment]
Там не ссылка, там вся карта дублируеться.
