### ISSUE TITLE
Не добавляются ?start= в карту сайта

### ISSUE THREAD

**Issue by damarkuzz** [Joomline/jlsitemap#74]
Здравствуйте. При формировании карты сайта не создаются добавляются ссылки формата` site.ru/article?start=1`
Как не пытаюсь, не настраиваю - игнорируются, хотя которые начинаются с `?view=...` без проблем

**Comment by sergeytolkachyov** [comment]
Это страницы пагинации. Они и не должны попадать в карту сайта.
