### ISSUE TITLE
pdfs ignored on sitemap

### ISSUE THREAD

**Issue by hpgodwin** [Joomline/jlsitemap#79]
Using JL Sitemap on https://www.uab.edu/research/home/
Sitemap: https://www.uab.edu/research/home/sitemap.xml
and none of our pdfs show on the sitemap, though they are 38 linked on this page: https://www.uab.edu/research/home/osp-researchers-toolkit/forms
PDFs: https://www.uab.edu/research/home/images/CIRB/RPLpdf.pdf
They are all stored in the images/documents folder of the directory, is anything in the images folder just being hidden off the sitemap?

**Comment by sergeytolkachyov** [comment]
This component is not for files on your server. It combine xml sitemap only for Joomla components
