### ISSUE TITLE
Запуск по расписанию Joomla 4

### ISSUE THREAD

**Issue by mediafoks** [Joomline/jlsitemap#82]
Добрый день уважаемые разработчики!
Я так понимаю, что разработка и поддержка данного плагина прекращена? Больше года никаких изменений.
Cron на Joomla 4 так и не работает (на Joomla 3 всё прекрасно).
Ответьте пожалуйста, стоит ли ждать каких-либо изменений?

**Comment by zikkuratvk** [comment]
Мы выпустим фиксы для joomla 4 в ближайшее время.

**Comment by zikkuratvk** [comment]
84e73d8998b11d543f842f0313c81bce8375fede
