### ISSUE TITLE
Как исправит шаблон с картой сайта?

### ISSUE THREAD

**Issue by Retile5** [Joomline/jlsitemap#83]
Как, например, увеличить или изменить шрифт в сгенерированной карте сайта?

**Comment by zikkuratvk** [comment]
Зачем вообще увеличивать шрифт в карте сайта. Это исключительно инструмент для поисковых роботов. Людям в целом там делать нечего.

**Comment by Retile5** [comment]
В смысле??? Я этим компонентом генерирую html с картой сайта ИМЕННО для посетителей! Генерирую через https://mysite.ru/index.php?option=com_jlsitemap&view=html&key=1

**Comment by zikkuratvk** [comment]
Это есть html карта сайта. Наложите css стили какие вам требуется. И даже она не для посетителей, а больше для поисковых роботов.

**Comment by Retile5** [comment]
Не подскажете как это сделать?

**Comment by zikkuratvk** [comment]
к #JLSitemap указываете необходимые вам css стили.
