### ISSUE TITLE
Deprecated в верии 1.12.0

### ISSUE THREAD

**Issue by Sulpher** [Joomline/jlsitemap#87]
JL sitemap 1.12.0
Joomla 4.3.0
Версия PHP | 8.1.11
```

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www//html/components/com_jlsitemap/models/sitemap.php on line 511

Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /var/html/components/com_jlsitemap/models/sitemap.php on line 918

Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /var//html/plugins/jlsitemap/content/content.php on line 214

Deprecated: DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /var//html/libraries/src/Date/Date.php on line 126
```

**Comment by kosh2323** [comment]
Да-да тоже самое, будут ли исправления под версию PHP 8.1?

**Comment by Magnumv44** [comment]
Если компомнент еще развивается, то UP, и так же есть еще ошибка:
`PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in D:\Webserver\domains\mytest\components\com_jlsitemap\models\sitemap.php on line 511`

**Comment by kosh2323** [comment]
> Если компонент еще развивается, то UP. Поддержка PHP 8.1 и Joomla 5 (в последнем говорит о возможной проблеме с плагином планировщика в процессе обновления)

Есть предположение, что продукт не развивается, т.к. за 1,5 года ни разу не обновили, отсюда и проблемы...

**Comment by Sulpher** [comment]
Это не является ошибкой. это нотис - предупреждение. скрипт отрабатывает. понизьте уровень показа ошибок.
но нотис просто правильнее поправить, чтобы его не было. тем не менее, на работоспособность это не влияет.
а вот на Joomla 5 не тестировал.

**Comment by Magnumv44** [comment]
> нотис не является ошибкой. это предупреждение. скрипт отрабатывает. понизьте уровень показа ошибок. но нотис просто правильнее поправить, чтобы его не было. тем не менее, на работоспособность это не влияет. а вот на Joomla 5 не тестировал.

Сам компонент вроде бы работает, ругается только на плагин планировщика. Но если компонент, не развивается, то жаль=(

**Comment by kosh2323** [comment]
> нотис не является ошибкой. это предупреждение. скрипт отрабатывает. понизьте уровень показа ошибок. но нотис просто правильнее поправить, чтобы его не было. тем не менее, на работоспособность это не влияет. а вот на Joomla 5 не тестировал.

Да, понятно, но откуда такие предположения о том, что проект может загнуться. PHP 8.1 был выпущен в ноябре 21-го года, а версия компонента 1.12.0 была выпущена в мае 22-го, и с тех пор не обновлялась, с версией PHP 8.1 выдает предупреждения(Deprecated). И уже тогда, когда была выпущена версия 1.12.0, она уже выдавала "Deprecated", но разработчики все равно зарелизили. Прошло полтора года, но так и не пофиксили, это может означать только одно, продуктом никто не занимается, и возможно он уже и заброшен. Может некогда заниматься, может некому, может ввиду его бесплатной версии и т.д. и т.п. Можно только гадать.

**Comment by sergeytolkachyov** [comment]
Выпущен релиз 2.0.0. Часть issue поправлены.
