### ISSUE TITLE
Сделать обработку регулярными выражениями полученной карты

### ISSUE THREAD

**Issue by progreccor** [Joomline/jlsitemap#9]
Для всяких странных желаний, которые могут придумать сеошники я бы предусмотрел такую возможность:
Запустить обработку регулярного выражения, которое задает пользователь с заменой найденной строки на указанную им.
Это универсальное решение думаю подойдет всем.

**Comment by Septdir** [comment]
@progreccor Как насчет такого. В настройках subform в виде таблицы, и там два поля. Регулярка и на что менять(Названия временные)
