### ISSUE TITLE
Articles/categories/etc. with noindex selected in Publishing settings shouldn't be in sitemap

### ISSUE THREAD

**Issue by Destroy666x** [Joomline/jlsitemap#95]
But they are. You can work around it with filters, would be nice for this to be automatic though, at least as an option.

**Comment by sergeytolkachyov** [comment]
This parameter is only for category page. Not for all nested articles.

**Comment by Destroy666x** [comment]
Standalone articles also get into sitemap despite having noindex

**Comment by sergeytolkachyov** [comment]
> Standalone articles also get into sitemap despite having noindex

Have you menu item for this article? I've tested again and for me standalone article with noindex isn't in sitemap.
